workflows:
  ios-testflight:
    integrations:
      app_store_connect: "Hi Car"    # tên bạn đặt trên Codemagic

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.hicar.ora.limited"   # đổi đúng bundle ID project bạn
      xcode: latest
      cocoapods: default

    scripts:
      - name: Setup FVM
        script: |
          dart pub global activate fvm
          export PATH="$PATH:$HOME/.pub-cache/bin"
          fvm install
      - name: Get Flutter packages
        script: fvm flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      # ↓ THÊM BƯỚC NÀY (quan trọng)
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build IPA
        script: |
          fvm flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
